# Generated by Django 5.0.1 on 2024-02-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_contact_user_following_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_likes'], name='social_post_total_l_b22ce0_idx'),
        ),
    ]
