# Generated by Django 5.0.1 on 2024-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_post_total_likes_post_social_post_total_l_b22ce0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
