# Generated by Django 5.0.1 on 2024-02-10 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_post_options_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
