# Generated by Django 5.0.1 on 2024-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_adminmessage_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmessage',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='adminmessage',
            index=models.Index(fields=['-date'], name='social_admi_date_73ff04_idx'),
        ),
    ]
