# Generated by Django 5.0.1 on 2024-02-10 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_adminmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
