# Generated by Django 5.0.1 on 2024-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_userslikeactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_activity',
            field=models.ManyToManyField(through='social.UsersLikeActivity', to='social.post'),
        ),
    ]
