# Generated by Django 5.0.1 on 2024-02-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_comment_body_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommentactivity',
            name='comment',
        ),
    ]
